version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./dataDB:/var/lib/postgresql/data
  backend:
    environment:
      BACKEND_PORT: 8080
      ADMIN_SECRET: ${ADMIN_SECRET}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    build: .
    depends_on:
      - "postgres"
    ports:
      - "${BACKEND_PORT}:8080"
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
